name: Run Pest Tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-pest-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: reshadman/common-github-workflows/.github/workflows/run-pest-tests.yml@main
